const resObj = [
  {
    product_id: 200089947,
    product_name: "Medium Veg Pizza + Garlic Bread + Bevarage at 399",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/BY0C241XOELL.jpeg",
    rating: 4.3,
    product_code: "PRD882312993",
    price_without_tax: 399,
  },
  {
    product_id: 200089948,
    product_name: "Medium Non-Veg Pizza + Garlic Bread + Bevarage at 449",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/0WTRVFXF2GMI.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/0WTRVFXF2GMI.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/0WTRVFXF2GMI.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description:
      "A hearty non-veg meal that doesn't burn a hole in your pocket. Any Medium Non-Veg Pizza, Garlic Bread & Beverage!",
    big_description:
      "A hearty non-veg meal that doesn't burn a hole in your pocket. Any Medium Non-Veg Pizza, Garlic Bread & Beverage!",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 4.1,
    count_of_rating: 0,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 449,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 2,
    display_price: 471,
    share: null,
    product_feedback: null,
    product_code: "PRD462649684",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/0WTRVFXF2GMI.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 449,
    tax_amount: 0,
  },
  {
    product_id: 200084636,
    product_name: "Tracer Bullet Boundary Combo (serves 6)",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/DELBNLOYKAZH.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/DELBNLOYKAZH.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/DELBNLOYKAZH.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description: "2 Pizza + 1 Garlic Bread + 2 Drinks & 1 Dessert",
    big_description: "2 Pizza + 1 Garlic Bread + 2 Drinks & 1 Dessert",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 4,
    count_of_rating: 6,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 799,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 3,
    display_price: 839,
    share: null,
    product_feedback: null,
    product_code: "PRD685248259",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/DELBNLOYKAZH.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 799,
    tax_amount: 0,
  },
  {
    product_id: 200084641,
    product_name: "Crisp Boundary Combo (Serves 8)",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/VR0PHJOSQZVS.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/VR0PHJOSQZVS.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/VR0PHJOSQZVS.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description: "4 Medium Thin Crust Pizza",
    big_description: "4 Medium Thin Crust Pizza",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 3.6,
    count_of_rating: 0,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 1249,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 4,
    display_price: 1311,
    share: null,
    product_feedback: null,
    product_code: "PRD666092902",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/VR0PHJOSQZVS.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 1249,
    tax_amount: 0,
  },
  {
    product_id: 200084635,
    product_name: "Classic Boundary Combo (Serves 8)",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/60AA5JKZYZ0H.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/60AA5JKZYZ0H.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/60AA5JKZYZ0H.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description: "4 Medium Pizza Combo",
    big_description: "4 Medium Pizza Combo",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 3.9,
    count_of_rating: 0,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 1249,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 5,
    display_price: 1311,
    share: null,
    product_feedback: null,
    product_code: "PRD278583574",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/60AA5JKZYZ0H.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 1249,
    tax_amount: 0,
  },
  {
    product_id: 200084637,
    product_name: "Thats A Maximum Combo (Serves 8)",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/MGKQG9QOMFAE.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/MGKQG9QOMFAE.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/MGKQG9QOMFAE.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description: "3 Pizza + 2 Garlic Bread + 2 Drinks & 2 Desserts",
    big_description: "3 Pizza + 2 Garlic Bread + 2 Drinks & 2 Desserts",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 2.6,
    count_of_rating: 0,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 1299,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 6,
    display_price: 1364,
    share: null,
    product_feedback: null,
    product_code: "PRD558478006",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/MGKQG9QOMFAE.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 1299,
    tax_amount: 0,
  },
  {
    product_id: 200084638,
    product_name: "PKMKB Combo (Serves 11)",
    hsn_code: "996331",
    product_imageUrl:
      "https://rp-media.faasos.io/catalog/images/DIPAGP2ZLFUR.jpeg",
    image_es: "https://rp-media.faasos.io/catalog/images/DIPAGP2ZLFUR.jpeg",
    image_es_mobweb:
      "https://rp-media.faasos.io/catalog/images/DIPAGP2ZLFUR.jpeg",
    benefits: "Instant Energy",
    sure_points: 0,
    product_category_id: 1,
    small_description:
      "Pizza Khao, Maze Karo Bhai (4 Medium Pizza + 2 Garlic Bread + 2 Bevarage + 2 Dessert)",
    big_description:
      "Pizza Khao, Maze Karo Bhai (4 Medium Pizza + 2 Garlic Bread + 2 Bevarage + 2 Dessert)",
    is_veg: 0,
    is_customizable: 0,
    is_customizable_group: 1,
    customization_limit: null,
    spice_level: null,
    bought_count: null,
    rating: 5,
    count_of_rating: 0,
    is_available: 1,
    is_active: 1,
    is_back_calculate_tax: 0,
    tax_category: 7,
    price: 1971,
    eatsure_exclusive_savings: 0,
    store_id: 10240,
    virtual_store_code: "VST266278327",
    brand_id: 21,
    client_source_id: 13,
    offer_price: 0,
    details: {
      big_description: null,
      nutritional: [],
      tags: [],
      nutritional_information: [],
      ingredients: null,
      preparation_steps: [],
      facts: "",
      nutritional_information_header: "Nutritional value",
      nutritional_information_message:
        "Value based on default selection, may vary with customisation",
    },
    feature_tags: [],
    tags: [],
    promo_tags: [],
    ml_tags: [],
    offer_tags: [],
    is_featured: 0,
    brand_name: "Ovenstory",
    brand_banner_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_logo_image:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_rectangle_logo:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    brand_banner_image_es:
      "https://product-assets.faasos.io/eatsure_cms/production/98325368-6a0a-49f9-ada1-8bb7b14bdd65.jpg",
    brand_banner_image_large:
      "https://rp-media.faasos.io/catalog/images/0TB1SAAY2Z.jpeg",
    sequence: 7,
    display_price: 2070,
    share: null,
    product_feedback: null,
    product_code: "PRD528896879",
    is_switched_off: 0,
    switch_off_msg: "",
    brand_display_name: "Ovenstory",
    is_variation: 0,
    is_advance_order: false,
    is_crosslisted: false,
    images: [
      {
        image_url:
          "https://rp-media.faasos.io/catalog/images/DIPAGP2ZLFUR.jpeg",
        sequence: 1,
      },
    ],
    price_without_tax: 1971,
    tax_amount: 0,
  },
];

export default resObj;
